events {
    worker_connections 1024;
}

http {
    # Reverse proxy ไปยัง Strapi application
    upstream strapi {
        server s2app:1337;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://strapi;
        }
    }
}
